"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_SETTINGS = exports.POKEMON_PATHS = exports.DAILY_GOAL_TARGET = exports.BADGES = exports.getXpToNextLevel = exports.getLevelFromXp = exports.LEVEL_THRESHOLDS = exports.AVATARS = void 0;
var profile_1 = require("./profile");
Object.defineProperty(exports, "AVATARS", { enumerable: true, get: function () { return profile_1.AVATARS; } });
Object.defineProperty(exports, "LEVEL_THRESHOLDS", { enumerable: true, get: function () { return profile_1.LEVEL_THRESHOLDS; } });
Object.defineProperty(exports, "getLevelFromXp", { enumerable: true, get: function () { return profile_1.getLevelFromXp; } });
Object.defineProperty(exports, "getXpToNextLevel", { enumerable: true, get: function () { return profile_1.getXpToNextLevel; } });
var gamification_1 = require("./gamification");
Object.defineProperty(exports, "BADGES", { enumerable: true, get: function () { return gamification_1.BADGES; } });
Object.defineProperty(exports, "DAILY_GOAL_TARGET", { enumerable: true, get: function () { return gamification_1.DAILY_GOAL_TARGET; } });
Object.defineProperty(exports, "POKEMON_PATHS", { enumerable: true, get: function () { return gamification_1.POKEMON_PATHS; } });
var settings_1 = require("./settings");
Object.defineProperty(exports, "DEFAULT_SETTINGS", { enumerable: true, get: function () { return settings_1.DEFAULT_SETTINGS; } });
